services:
  signalytics:
    build:
      context: .
      target: dev
    environment:
      DATABASE_URL: mysql://root:app@mysql:3306/app
      LOG_LEVEL: trace
    volumes:
      - .:/app

  caddy:
    image: caddy:2.11
    ports:
      - "8080:80"
    volumes:
      - ./conf/Caddyfile:/etc/caddy/Caddyfile

  nginx:
    image: nginx:1.29
    ports:
      - "8081:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf

  mysql:
    image: mysql:9.5
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
